### ISSUE TITLE
When I retrieval images, my input is label and  an image. Is that right? Does it contradicts with "CBIR" concept?

### ISSUE THREAD

**Issue by xiaozhi2015** [caoyue10/cvpr17-dvsq#8]

**Comment by xiaozhi2015** [comment]
@caoyue10  Looking forward to replys.

**Comment by caoyue10** [comment]
CBIR is defined as that given image query (only image w/o label), return the images from the image database which are the most similar to the query.

**Comment by xiaozhi2015** [comment]
Thx a lot! ^_^

**Comment by xiaozhi2015** [comment]
But in Wiki I saw the description as ----"Content-based" means that the search analyzes the contents of the image rather than the metadata such as keywords, tags, or descriptions associated with the image. The term "content" in this context might refer to colors, shapes, textures, or any other information that can be derived from the image itself.  
@caoyue10

**Comment by xiaozhi2015** [comment]
BTW, how can I do image retrieval without any label infos using your code？

**Comment by bl0** [comment]
Actually, You don't need the label for retrieval, we only use the label for performance evaluation.

**Comment by xiaozhi2015** [comment]
Much thx! @bl0  And can I train the model without any label infos?
