### ISSUE TITLE
模型加载问题

### ISSUE THREAD

**Issue by ShenQuanYang** [caoyue10/cvpr17-dvsq#9]
您好，我运行代码的时候出现了一个错误：OSError: Failed to interpret file 'models/reference_pretrain.npy' as a pickle，请问这个问题该怎么解决呢？

**Comment by bl0** [comment]
可以换一下python版本试试。

**Comment by ShenQuanYang** [comment]
换成python3.5可以吗？

**Comment by bl0** [comment]
试试python2

**Comment by bl0** [comment]
这个代码实际上已经没有维护了，可以试试这个：https://github.com/thulab/DeepHash. dvsq也在这下面。

**Comment by ShenQuanYang** [comment]
谢谢
